name: Apply Overrides

on:
  workflow_call:
    inputs:
      override_file:
        required: true
        type: string
      schema_file:
        required: true
        type: string

jobs:
  apply-overrides:
    name: "Applies the overrides to the schema"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install yq 
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Run the script
      run: |
        for k in $(yq '. | keys | .[]' ${{ inputs.override_file }}); do
          newDescription=$(yq ".\"$k\"" ${{ inputs.override_file }});
          # Indent 4; output as json; edit in place
          yq  -I 4 -o json -i "$k.description = \"${newDescription}\"" ${{ inputs.schema_file }}
        done

    - name: upload api schema
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.schema_file }}
        path: ${{ inputs.schema_file }}
        retention-days: 1
